/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.paulofernandes.example;

import java.util.logging.Logger;

public class App {

    public static final String HELLO_WORLD = "Hello World!";

    public String getGreeting() {
        return HELLO_WORLD;
    }

    public static void main(String[] args) {
        final App app = new App();
        final Logger logger = Logger.getLogger(app.getClass().getName());
        logger.info(app.getGreeting());
    }
}
