/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.paulofernandes.example;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {

    private static final String APP_SHOULD_HAVE_A_GREETING = "app should have a greeting";
    private App classUnderTest;

    @BeforeEach
    void setUp() {
        classUnderTest = new App();
    }

    @Test
    public void appHasAGreeting() {
        assertNotNull(classUnderTest.getGreeting(), APP_SHOULD_HAVE_A_GREETING);
    }
}
